image: javiersantos/android-ci:latest

stages:
  - pages

variables:
  GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.caching=true'
  GRADLE_USER_HOME: '.gradle'

before_script:
  - chmod +x gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

pages:
  tags:
    - pages
  stage: pages
  before_script:
    - curl -OL https://github.com/noproxy/gradle-plugin-kit/raw/master/subprojects/init-scripts/src/main/groovy/docs.gradle
  script:
    - ./gradlew --init-script docs.gradle :asciidoctor
  after_script:
    - mv docs/build/docs/asciidoc public
  artifacts:
    paths:
      - public
  only:
    - master